Global:
  reader_config: configs/picodet/picodet_s_300_custom.yml
  include_nms: True
  Evaluation: True
  model_dir: output_inference/picodet_s_300_custom
  model_filename: model.pdmodel
  params_filename: model.pdiparams

Distillation:
  alpha: 1.0
  loss: l2

ChannelPrune:
  pruned_ratio: 0.5
  criterion: l1_norm
  prune_params_name: ["conv2d_10.w_0",
"conv2d_12.w_0",
"conv2d_15.w_0",
"conv2d_14.w_0"]

QuantAware:
  use_pact: true
  activation_quantize_type: 'moving_average_abs_max'
  weight_bits: 8
  activation_bits: 8
  quantize_op_types:
  - conv2d
  - depthwise_conv2d
#  is_full_quantize: true

TrainConfig:
  train_iter: 400
  eval_iter: 10
  learning_rate:  
    type: CosineAnnealingDecay
    learning_rate: 0.000001
    T_max: 8000
  optimizer_builder:
    optimizer:
      type: SGD
    weight_decay: 4.0e-05


