Global:
  reader_config: configs/ssd/ssd_mobilenet_v1_custom.yml
  include_nms: True
  Evaluation: True
  model_dir: output_inference/ssd_mobilenet_v1_custom
  model_filename: model.pdmodel
  params_filename: model.pdiparams

Distillation:
  alpha: 1.0
  loss: l2

ChannelPrune:
  pruned_ratio: 0.2

QuantAware:
  use_pact: true
  activation_quantize_type: 'moving_average_abs_max'
  weight_bits: 8
  activation_bits: 8
  quantize_op_types:
  - conv2d
  - depthwise_conv2d

TrainConfig:
  train_iter: 10
  eval_iter: 10
  learning_rate:  
    type: CosineAnnealingDecay
    learning_rate: 0.0001
    T_max: 6000
  optimizer_builder:
    optimizer: 
      type: SGD
    weight_decay: 4.0e-05

