_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/picodet_v2_custom.yml',
  '_base_/optimizer_300e.yml',
  '_base_/picodet_288_reader.yml',
]

weights: output/picodet_s_288_custom/best_model.pdparams
pretrain_weights: output/picodet_s_288_custom/best_model.pdparams

find_unused_parameters: True
use_ema: true
epoch: 650
snapshot_epoch: 2

worker_num: 1

TrainReader:
  batch_size: 32

LearningRate:
  base_lr: 0.0032
  schedulers:
  - !CosineDecay
    max_epochs: 650
  - !LinearWarmup
    start_factor: 0.1  # start_lr = base_lr * start_factor
    steps: 300
