epoch: 300

LearningRate:
  base_lr: 0.32
  schedulers:
  - name: CosineDecay
    max_epochs: 300
  - name: LinearWarmup
    start_factor: 0.1
    steps: 300

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
    # type: Adam
    # weight_decay: 4.0e-05
  regularizer:
    factor: 0.00004
    type: L2
