architecture: PicoDet
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/LCNet_x1_5_pretrained.pdparams

PicoDet:
  backbone: LCNet
  neck: LCPAN
#  backbone: MobileNet
#  neck: FPN
  head: PicoHeadV2

LCNet:
  scale: 0.75
  feature_maps: [3, 4, 5]

LCPAN:
  out_channels: 8  # channel too small, 48?
  use_depthwise: True
#  num_features: 4
  num_features: 3

MobileNet:
  norm_decay: 0.
  scale: 1
  conv_learning_rate: 0.1
#  extra_block_filters: [[256, 512], [128, 256], [128, 256], [64, 128]]
#  with_extra_blocks: True
#  feature_maps: [11, 13, 14, 15, 16, 17]
#  feature_maps: [11, 13, 14, 15]
#  feature_maps: [6, 7, 8, 9]
  feature_maps: [3, 5, 10]

#FPN:
#  out_channel: 96

PicoHeadV2:
  conv_feat:
    name: PicoFeat
    feat_in: 8
    feat_out: 8
    num_convs: 2
#    num_fpn_stride: 4
    num_fpn_stride: 3
    norm_type: bn
    share_cls_reg: True
    use_se: False
  feat_in_chan: 8
#  fpn_stride: [8, 16, 32, 64]
  fpn_stride: [8, 16, 32]
#  fpn_stride: [2, 4, 8, 16]
  prior_prob: 0.01
  reg_max: 7
  cell_offset: 0.5
  grid_cell_scale: 5.0
  static_assigner_epoch: 100
  use_align_head: False
  static_assigner:
    name: ATSSAssigner
    topk: 9
    force_gt_matching: False
  assigner:
    name: TaskAlignedAssigner
    topk: 13
    alpha: 1.0
    beta: 6.0
  loss_class:
    name: VarifocalLoss
    use_sigmoid: False
    iou_weighted: True
    loss_weight: 1.0
  loss_dfl:
    name: DistributionFocalLoss
    loss_weight: 0.5
  loss_bbox:
    name: GIoULoss
    loss_weight: 2.5
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 100
    score_threshold: 0.025
    nms_threshold: 0.6
