_BASE_: [
  '../datasets/voc.yml',
  '../runtime.yml',
  '_base_/optimizer_1700e.yml',
  '_base_/ssdlite_mobilenet_v3_small_320.yml',
  '_base_/ssdlite300_reader.yml',
]
epoch: 20000
snapshot_epoch: 5
pretrain_weights: output/ssdlite_mobilenet_v3_small_custom/best_model.pdparams
weights: ../output/ssdlite_mobilenet_v3_small_custom/model_final

# metric: COCO
metric: VOC

num_classes: 4

TrainDataset:
  !VOCDataSet
    dataset_dir: dataset/alum/
    anno_path: train.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']


EvalDataset:
  !VOCDataSet
    dataset_dir: dataset/alum/
    anno_path: val.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  !ImageFolder
    anno_path: dataset/alum/label_list.txt

bufsize: 1

worker_num: 4

