# Weights of yolov3_mobilenet_v1_voc
pretrain_weights: https://paddledet.bj.bcebos.com/models/yolov3_mobilenet_v1_270e_voc.pdparams
slim: Pruner

Pruner:
  criterion: fpgm
  pruned_params: [
 'backbone.blocks6.1.pw_conv.conv',
 'backbone.blocks6.1.se.conv2',
 'backbone.blocks6.1.dw_conv.conv']
  pruned_ratios: [0.4,0.4,0.4]
  print_params: True
