architecture: YOLOv3
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/MobileNetV3_large_x0_5_pretrained.pdparams
norm_type: sync_bn
use_ema: true
ema_decay: 0.9998

YOLOv3:
  backbone: MobileNetV3
  neck: PPYOLOTinyFPN
  yolo_head: YOLOv3Head
  post_process: BBoxPostProcess

MobileNetV3:
  model_name: large
  scale: .5
  with_extra_blocks: false
  extra_block_filters: []
  feature_maps: [7, 13, 16]

PPYOLOTinyFPN:
  detection_block_channels: [160, 128, 96]
  spp: true
  drop_block: true

YOLOv3Head:
  anchors: [[16, 25],[29, 64],[45, 42],[44, 59],[130, 36],[36, 155],[104, 58],[134, 92],[75, 180]]
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  loss: YOLOv3Loss

YOLOv3Loss:
  ignore_thresh: 0.5
  downsample: [32, 16, 8]
  label_smooth: false
  scale_x_y: 1.05
  iou_loss: IouLoss

IouLoss:
  loss_weight: 2.5
  loss_square: true

BBoxPostProcess:
  decode:
    name: YOLOBox
    conf_thresh: 0.005
    downsample_ratio: 32
    clip_bbox: true
    scale_x_y: 1.05
  nms:
    name: MultiClassNMS
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    score_threshold: 0.005
